name: New Allocation Request
description: Request a New Allocation
title: "New Allocation for [Org Name] "
labels: ["new allocation"]
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: organization
    attributes:
      label: What organization is requesting an allocation?
      placeholder: N/A
    validations:
      required: true
  - type: input
    id: count
    attributes:
      label: How many sids are required?
      placeholder: "10,000"
    validations:
      required: true
  - type: textarea
    id: links
    attributes:
      label: Please provide reference links
      description: Include any links which can be used as a reference to further document the use of the allocated sid range.
    validations:
      required: False
  - type: checkboxes
    id: engines
    attributes:
      label: IDS Engine
      description: For which IDS Engine(s) will the signatures be produced?
      options:
        - label: Snort
        - label: Suricata
          required: true
  - type: textarea
    id: download_links
    attributes:
      label: Download Links
      description: Please provide any links, redacting any \"secret code\" as needed
      placeholder: https://rules.emergingthreatspro.com/%(secret-code)s/suricata-%(__version__)s/etpro.rules.tar.gz
